# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.srcs/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/system_Pro_FPGA_ctrl_0_2.xci
# IP: The module: 'system_Pro_FPGA_ctrl_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/div_gen_hex_2_dec_1/div_gen_hex_2_dec.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_hex_2_dec || ORIG_REF_NAME==div_gen_hex_2_dec} -quiet] -quiet

# IP: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/blk_mem_gen_1_1/blk_mem_gen_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/mult_gen_0_1/mult_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/blk_mem_gen_1_1/blk_mem_gen_1_ooc.xdc

# IP: D:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.srcs/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/system_Pro_FPGA_ctrl_0_2.xci
# IP: The module: 'system_Pro_FPGA_ctrl_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/div_gen_hex_2_dec_1/div_gen_hex_2_dec.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_hex_2_dec || ORIG_REF_NAME==div_gen_hex_2_dec} -quiet] -quiet

# IP: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/blk_mem_gen_1_1/blk_mem_gen_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/mult_gen_0_1/mult_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0} -quiet] -quiet

# XDC: d:/ASUS-PC/Desktop/temporary/test/Vivado2021/2025.5.28-1/Mini_ctrl_brd_zynq/Mini_ctrl_brd_zynq.gen/sources_1/bd/system/ip/system_Pro_FPGA_ctrl_0_2/src/blk_mem_gen_1_1/blk_mem_gen_1_ooc.xdc
